osx_image: xcode7.3
language: objective-c
xcode_project: AZTools.xcodeproj
script: xcodebuild -project AZTools.xcodeproj -scheme "AZTools" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
